//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUSSISADTeam10API.Models.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class adjustmentdetail
    {
        public int adjid { get; set; }
        public int itemid { get; set; }
        public Nullable<int> adjustedqty { get; set; }
        public string reason { get; set; }
    
        public virtual adjustment adjustment { get; set; }
        public virtual item item { get; set; }
    }
}
