//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUSSISADTeam10API.Models.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventorytransaction
    {
        public int tranid { get; set; }
        public System.DateTime datetime { get; set; }
        public int invid { get; set; }
        public int itemid { get; set; }
        public int trantype { get; set; }
        public int qty { get; set; }
        public string remark { get; set; }
    
        public virtual inventory inventory { get; set; }
        public virtual item item { get; set; }
    }
}
