//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUSSISADTeam10API.Models.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemTrendAnalysi
    {
        public string DepartmentName { get; set; }
        public string Item_Name { get; set; }
        public Nullable<int> Item_Usage { get; set; }
        public int deptid { get; set; }
        public int itemid { get; set; }
        public Nullable<int> Monthofreq { get; set; }
        public Nullable<int> Yearofreq { get; set; }

        public Nullable<int> firstdeptname { get; set; }
        public Nullable<int> seconddepatname { get; set; }
        public Nullable<int> thirddeptname { get; set; }

    }
}
