//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUSSISADTeam10API.Models.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class lockercollectionpoint
    {
        public int lockerid { get; set; }
        public string lockername { get; set; }
        public string lockersize { get; set; }
        public int cpid { get; set; }
        public int status { get; set; }
    
        public virtual collectionpoint collectionpoint { get; set; }
    }
}
