//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUSSISADTeam10API.Models.DBModels
{
    using System;
    
    public partial class MonthlyItemUsage
    {
        public string Item_ { get; set; }
        public Nullable<int> Usage_Item { get; set; }
        public Nullable<int> Month_Name { get; set; }
        public Nullable<int> year { get; set; }
        public string supname { get; set; }
        public int supid { get; set; }
    }
}
