//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUSSISADTeam10API.Models.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyItemUsageByHOD
    {
        public string Item { get; set; }
        public string Category { get; set; }
        public int Quantity { get; set; }
        public string Unit_of_Measurement { get; set; }
        public int deptid { get; set; }
        public string deptname { get; set; }
        public Nullable<int> MonthProduce { get; set; }
        public Nullable<int> YearProduce { get; set; }
    }
}
