//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUSSISADTeam10API.Models.DBModels
{
    using System;
    
    public partial class NumberofRequsitions
    {
        public Nullable<int> NumberofReq { get; set; }
        public int reqid { get; set; }
        public string deptname { get; set; }
        public Nullable<int> ProceduceMonth { get; set; }
        public Nullable<int> ProceduceYear { get; set; }
    }
}
