//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LUSSISADTeam10API.Models.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class requisition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public requisition()
        {
            this.disbursements = new HashSet<disbursement>();
            this.outstandingrequisitions = new HashSet<outstandingrequisition>();
            this.requisitiondetails = new HashSet<requisitiondetail>();
        }
    
        public int reqid { get; set; }
        public Nullable<int> raisedby { get; set; }
        public Nullable<int> approvedby { get; set; }
        public int deptid { get; set; }
        public int cpid { get; set; }
        public int status { get; set; }
        public Nullable<System.DateTime> reqdate { get; set; }
    
        public virtual collectionpoint collectionpoint { get; set; }
        public virtual department department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<disbursement> disbursements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<outstandingrequisition> outstandingrequisitions { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<requisitiondetail> requisitiondetails { get; set; }
    }
}
